export const CRYPTOS: Record<string, string> = {
	AAVE: 'Aave',
	ADA: 'Cardano',
	ALGO: 'Algorand',
	APT: 'Aptos',
	ARB: 'Arbitrum',
	ATOM: 'Cosmos',
	AVAX: 'Avalanche',
	BCH: 'Bitcoin Cash',
	BGB: 'Bitget Token',
	BNB: 'Binance Coin',
	BONK: 'Bonk',
	BTC: 'Bitcoin',
	CRO: 'Cronos',
	DAI: 'Dai',
	DOGE: 'Dogecoin',
	DOT: 'Polkadot',
	ENA: 'Ethena',
	ETC: 'Ethereum Classic',
	ETH: 'Ethereum',
	FDUSD: 'First Digital USD',
	FET: 'Artificial Superintelligence Alliance',
	FIL: 'Filecoin',
	FLR: 'Flare',
	FORM: 'Four',
	GT: 'GateToken',
	HBAR: 'Hedera',
	HYPE: 'Hyperliquid',
	ICP: 'Internet Computer',
	INJ: 'Injective',
	IP: 'Story',
	JUP: 'Jupiter',
	KAS: 'Kaspa',
	KCS: 'KuCoin Token',
	LEO: 'UNUS SED LEO',
	LINK: 'Chainlink',
	LTC: 'Litecoin',
	MNT: 'Mantle',
	NEAR: 'NEAR Protocol',
	OKB: 'OKB',
	ONDO: 'Ondo',
	PEPE: 'Pepe',
	PENGU: 'Pudgy Penguins',
	PI: 'Pi',
	POL: 'POL',
	PYTH: 'Pyth Network',
	QNT: 'Quant',
	RENDER: 'Render',
	SEI: 'Sei',
	SHIB: 'Shiba Inu',
	SKY: 'Sky',
	SOL: 'Solana',
	SUI: 'Sui',
	TAO: 'Bittensor',
	TIA: 'Celestia',
	TON: 'Toncoin',
	TRUMP: 'OFFICIAL TRUMP',
	TRX: 'TRON',
	UNI: 'Uniswap',
	USDC: 'USDC',
	USDE: 'Ethena USDe',
	USD1: 'World Liberty Financial USD',
	USDT: 'Tether USDt',
	VET: 'VeChain',
	WLD: 'Worldcoin',
	XDC: 'XDC Network',
	XLM: 'Stellar',
	XMR: 'Monero',
	XRP: 'XRP',
};