export const CURRENCIES: Record<string, string> = {
	AED: 'Dirham SAE',
	AFN: 'Afghánský afghání',
	ALL: 'Albánský lek',
	AMD: 'Arménský dram',
	ANG: 'Zlatý Nizozemských Antil',
	AOA: 'Angolská kwanza',
	ARS: 'Argentinské peso',
	AUD: 'Australský dolar',
	AWG: 'Arubský florin',
	AZN: 'Ázerbájdžánský manat',
	BAM: 'Konvertibilní marka',
	BBD: 'Barbadoský dolar',
	BDT: 'Bangladéšská taka',
	BGN: 'Bulharský lev',
	BHD: 'Bahrajnský dinár',
	BIF: 'Burundský frank',
	BMD: 'Bermudský dolar',
	BND: 'Brunejský dolar',
	BOB: 'Bolivijský boliviano',
	BRL: 'Brazilský real',
	BSD: 'Bahamský dolar',
	BTN: 'Bhútánský ngultrum',
	BWP: 'Botswanská pula',
	BYN: 'Běloruský rubl',
	BZD: 'Belizský dolar',
	CAD: 'Kanadský dolar',
	CDF: 'Konžský frank',
	CHF: 'Švýcarský frank',
	CLP: 'Chilské peso',
	CNY: 'Čínský jüan',
	COP: 'Kolumbijské peso',
	CRC: 'Kostarický colón',
	CUP: 'Kubánské peso',
	CVE: 'Kapverdské escudo',
	CZK: 'Česká koruna',
	DJF: 'Džibutský frank',
	DKK: 'Dánská koruna',
	DOP: 'Dominikánské peso',
	DZD: 'Alžírský dinár',
	EGP: 'Egyptská libra',
	ERN: 'Eritrejská nakfa',
	ETB: 'Etiopský birr',
	EUR: 'Euro',
	FJD: 'Fidžijský dolar',
	FKP: 'Falklandská libra',
	FOK: 'Faerská koruna',
	GBP: 'Britská libra',
	GEL: 'Gruzínský lari',
	GGP: 'Guernseyská libra',
	GHS: 'Ghanský cedi',
	GIP: 'Gibraltarská libra',
	GMD: 'Gambijský dalasi',
	GNF: 'Guinejský frank',
	GTQ: 'Guatemalský quetzal',
	GYD: 'Guyanský dolar',
	HKD: 'Hongkongský dolar',
	HNL: 'Honduraská lempira',
	HTG: 'Haitský gourde',
	HUF: 'Maďarský forint',
	IDR: 'Indonéská rupie',
	ILS: 'Izraelský šekel',
	IMP: 'Manská libra',
	INR: 'Indická rupie',
	IQD: 'Irácký dinár',
	IRR: 'Íránský rijál',
	ISK: 'Islandská koruna',
	JEP: 'Jerseyská libra',
	JMD: 'Jamajský dolar',
	JOD: 'Jordánský dinár',
	JPY: 'Japonský jen',
	KES: 'Keňský šilink',
	KGS: 'Kyrgyzský som',
	KHR: 'Kambodžský riel',
	KID: 'Kiribatský dolar',
	KMF: 'Komorský frank',
	KRW: 'Jihokorejský won',
	KWD: 'Kuvajtský dinár',
	KYD: 'Dolar Kajmanských ostrovů',
	KZT: 'Kazašské tenge',
	LAK: 'Laoský kip',
	LBP: 'Libanonská libra',
	LKR: 'Srílanská rupie',
	LRD: 'Liberijský dolar',
	LSL: 'Lesothský loti',
	LYD: 'Libyjský dinár',
	MAD: 'Marocký dirham',
	MDL: 'Moldavský lei',
	MGA: 'Malgašský ariary',
	MKD: 'Makedonský denár',
	MMK: 'Myanmarský kyat',
	MNT: 'Mongolský tugrik',
	MOP: 'Macajská pataca',
	MRU: 'Mauritánská ukíjá',
	MUR: 'Mauricijská rupie',
	MVR: 'Maledivská rupie',
	MWK: 'Malawiská kwacha',
	MXN: 'Mexické peso',
	MYR: 'Malajsijský ringgit',
	MZN: 'Mosambický metical',
	NAD: 'Namibijský dolar',
	NGN: 'Nigerijská naira',
	NIO: 'Nikaragujská córdoba',
	NOK: 'Norská koruna',
	NPR: 'Nepálská rupie',
	NZD: 'Novozélandský dolar',
	OMR: 'Ománský rijál',
	PAB: 'Panamská balboa',
	PEN: 'Peruánský sol',
	PGK: 'Papuánská kina',
	PHP: 'Filipínské peso',
	PKR: 'Pákistánská rupie',
	PLN: 'Polský zlotý',
	PYG: 'Paraguayský guaraní',
	QAR: 'Katarský rijál',
	RON: 'Rumunský lei',
	RSD: 'Srbský dinár',
	RUB: 'Ruský rubl',
	RWF: 'Rwandský frank',
	SAR: 'Saúdský rijál',
	SBD: 'Dolar Šalomounových ostrovů',
	SCR: 'Seychelská rupie',
	SDG: 'Súdánská libra',
	SEK: 'Švédská koruna',
	SGD: 'Singapurský dolar',
	SHP: 'Svatohelenská libra',
	SLE: 'Sierraleonský leone',
	SOS: 'Somálský šilink',
	SRD: 'Surinamský dolar',
	SSP: 'Jihosúdánská libra',
	STN: 'Svatotomášská dobra',
	SYP: 'Syrská libra',
	SZL: 'Svazijský lilangeni',
	THB: 'Thajský baht',
	TJS: 'Tádžický somoni',
	TMT: 'Turkmenský manat',
	TND: 'Tuniský dinár',
	TOP: 'Tonžská paʻanga',
	TRY: 'Turecká lira',
	TTD: 'Dolar Trinidadu a Tobaga',
	TVD: 'Tuvalský dolar',
	TWD: 'Tchajwanský dolar',
	TZS: 'Tanzanský šilink',
	UAH: 'Ukrajinská hřivna',
	UGX: 'Ugandský šilink',
	USD: 'Americký dolar',
	UYU: 'Uruguayské peso',
	UZS: 'Uzbecký sum',
	VES: 'Venezuelský bolívar',
	VND: 'Vietnamský dong',
	VUV: 'Vanuatský vatu',
	WST: 'Samojská tala',
	XAF: 'CFA frank',
	XCD: 'Východokaribský dolar',
	XDR: 'Zvláštní práva čerpání',
	XPF: 'CFP frank',
	YER: 'Jemenský rijál',
	ZAR: 'Jihoafrický rand',
	ZMW: 'Zambijská kwacha',
	ZWL: 'Zimbabwský dolar',
};

export const CURRENCIES_EN: Record<string, string> = {
  AED: 'United Arab Emirates Dirham',
  AFN: 'Afghan Afghani',
  ALL: 'Albanian Lek',
  AMD: 'Armenian Dram',
  ANG: 'Netherlands Antillean Guilder',
  AOA: 'Angolan Kwanza',
  ARS: 'Argentine Peso',
  AUD: 'Australian Dollar',
  AWG: 'Aruban Florin',
  AZN: 'Azerbaijani Manat',
  BAM: 'Bosnia-Herzegovina Convertible Mark',
  BBD: 'Barbadian Dollar',
  BDT: 'Bangladeshi Taka',
  BGN: 'Bulgarian Lev',
  BHD: 'Bahraini Dinar',
  BIF: 'Burundian Franc',
  BMD: 'Bermudian Dollar',
  BND: 'Brunei Dollar',
  BOB: 'Bolivian Boliviano',
  BRL: 'Brazilian Real',
  BSD: 'Bahamian Dollar',
  BTN: 'Bhutanese Ngultrum',
  BWP: 'Botswanan Pula',
  BYN: 'Belarusian Ruble',
  BZD: 'Belize Dollar',
  CAD: 'Canadian Dollar',
  CDF: 'Congolese Franc',
  CHF: 'Swiss Franc',
  CLP: 'Chilean Peso',
  CNY: 'Chinese Yuan',
  COP: 'Colombian Peso',
  CRC: 'Costa Rican Colón',
  CUP: 'Cuban Peso',
  CVE: 'Cape Verdean Escudo',
  CZK: 'Czech Koruna',
  DJF: 'Djiboutian Franc',
  DKK: 'Danish Krone',
  DOP: 'Dominican Peso',
  DZD: 'Algerian Dinar',
  EGP: 'Egyptian Pound',
  ERN: 'Eritrean Nakfa',
  ETB: 'Ethiopian Birr',
  EUR: 'Euro',
  FJD: 'Fijian Dollar',
  FKP: 'Falkland Islands Pound',
  FOK: 'Faroese Króna',
  GBP: 'British Pound Sterling',
  GEL: 'Georgian Lari',
  GGP: 'Guernsey Pound',
  GHS: 'Ghanaian Cedi',
  GIP: 'Gibraltar Pound',
  GMD: 'Gambian Dalasi',
  GNF: 'Guinean Franc',
  GTQ: 'Guatemalan Quetzal',
  GYD: 'Guyanaese Dollar',
  HKD: 'Hong Kong Dollar',
  HNL: 'Honduran Lempira',
  HTG: 'Haitian Gourde',
  HUF: 'Hungarian Forint',
  IDR: 'Indonesian Rupiah',
  ILS: 'Israeli Shekel',
  IMP: 'Isle of Man Pound',
  INR: 'Indian Rupee',
  IQD: 'Iraqi Dinar',
  IRR: 'Iranian Rial',
  ISK: 'Icelandic Króna',
  JEP: 'Jersey Pound',
  JMD: 'Jamaican Dollar',
  JOD: 'Jordanian Dinar',
  JPY: 'Japanese Yen',
  KES: 'Kenyan Shilling',
  KGS: 'Kyrgyzstani Som',
  KHR: 'Cambodian Riel',
  KID: 'Kiribati Dollar', // uncommon but follows pattern
  KMF: 'Comorian Franc',
  KRW: 'South Korean Won',
  KWD: 'Kuwaiti Dinar',
  KYD: 'Cayman Islands Dollar',
  KZT: 'Kazakhstani Tenge',
  LAK: 'Lao Kip',
  LBP: 'Lebanese Pound',
  LKR: 'Sri Lankan Rupee',
  LRD: 'Liberian Dollar',
  LSL: 'Lesotho Loti',
  LYD: 'Libyan Dinar',
  MAD: 'Moroccan Dirham',
  MDL: 'Moldovan Leu',
  MGA: 'Malagasy Ariary',
  MKD: 'Macedonian Denar',
  MMK: 'Myanmar Kyat',
  MNT: 'Mongolian Tugrik',
  MOP: 'Macanese Pataca',
  MRU: 'Mauritanian Ouguiya',
  MUR: 'Mauritian Rupee',
  MVR: 'Maldivian Rufiyaa',
  MWK: 'Malawian Kwacha',
  MXN: 'Mexican Peso',
  MYR: 'Malaysian Ringgit',
  MZN: 'Mozambican Metical',
  NAD: 'Namibian Dollar',
  NGN: 'Nigerian Naira',
  NIO: 'Nicaraguan Córdoba',
  NOK: 'Norwegian Krone',
  NPR: 'Nepalese Rupee',
  NZD: 'New Zealand Dollar',
  OMR: 'Omani Rial',
  PAB: 'Panamanian Balboa',
  PEN: 'Peruvian Sol',
  PGK: 'Papua New Guinean Kina',
  PHP: 'Philippine Peso',
  PKR: 'Pakistani Rupee',
  PLN: 'Polish Zloty',
  PYG: 'Paraguayan Guaraní',
  QAR: 'Qatari Rial',
  RON: 'Romanian Leu',
  RSD: 'Serbian Dinar',
  RUB: 'Russian Ruble',
  RWF: 'Rwandan Franc',
  SAR: 'Saudi Riyal',
  SBD: 'Solomon Islands Dollar',
  SCR: 'Seychellois Rupee',
  SDG: 'Sudanese Pound',
  SEK: 'Swedish Krona',
  SGD: 'Singapore Dollar',
  SHP: 'Saint Helena Pound',
  SLE: 'Sierra Leonean Leone',
  SOS: 'Somali Shilling',
  SRD: 'Surinamese Dollar',
  SSP: 'South Sudanese Pound',
  STN: 'São Tomé and Príncipe Dobra',
  SYP: 'Syrian Pound',
  SZL: 'Swazi Lilangeni',
  THB: 'Thai Baht',
  TJS: 'Tajikistani Somoni',
  TMT: 'Turkmenistani Manat',
  TND: 'Tunisian Dinar',
  TOP: "Tongan Paʻanga",
  TRY: 'Turkish Lira',
  TTD: 'Trinidad and Tobago Dollar',
  TVD: 'Tuvaluan Dollar',
  TWD: 'New Taiwan Dollar',
  TZS: 'Tanzanian Shilling',
  UAH: 'Ukrainian Hryvnia',
  UGX: 'Ugandan Shilling',
  USD: 'United States Dollar',
  UYU: 'Uruguayan Peso',
  UZS: 'Uzbekistan Som',
  VES: 'Venezuelan Bolívar',
  VND: 'Vietnamese Dong',
  VUV: 'Vanuatu Vatu',
  WST: 'Samoan Tala',
  XAF: 'CFA Franc BEAC',
  XCD: 'East Caribbean Dollar',
  XDR: 'Special Drawing Rights',
  XPF: 'CFP Franc',
  YER: 'Yemeni Rial',
  ZAR: 'South African Rand',
  ZMW: 'Zambian Kwacha',
  ZWL: 'Zimbabwean Dollar',
};