export const NAMEDAYS: string[][] = [
	[
		'je Nový rok, Den obnovy samostatného českého státu',
		'má svátek Karina',
		'má svátek Radmila',
		'má svátek Diana',
		'má svátek Dalimil',
		'má svátek Tři králové',
		'má svátek Vilma',
		'má svátek Čestmír',
		'má svátek Vladan',
		'má svátek Břetislav',
		'má svátek Bohdana',
		'má svátek Pravoslav',
		'má svátek Edita',
		'má svátek Radovan',
		'má svátek Alice',
		'má svátek Ctirad',
		'má svátek Drahoslav',
		'má svátek Vladislav',
		'má svátek Doubravka',
		'má svátek Ilona',
		'má svátek Běla',
		'má svátek Slavomír',
		'má svátek Zdeněk',
		'má svátek Milena',
		'má svátek Miloš',
		'má svátek Zora',
		'má svátek Ingrid',
		'má svátek Otýlie',
		'má svátek Zdislava',
		'má svátek Robin',
		'má svátek Marika',
	],
	[
		'má svátek Hynek',
		'má svátek Nela',
		'má svátek Blažej',
		'má svátek Jarmila',
		'má svátek Dobromila',
		'má svátek Vanda',
		'má svátek Veronika',
		'má svátek Milada',
		'má svátek Apolena',
		'má svátek Mojmír',
		'má svátek Božena',
		'má svátek Slavěna',
		'má svátek Věnceslav',
		'má svátek Valentýn',
		'má svátek Jiřina',
		'má svátek Ljuba',
		'má svátek Miloslava',
		'má svátek Gizela',
		'má svátek Patrik',
		'má svátek Oldřich',
		'má svátek Lenka',
		'má svátek Petr',
		'má svátek Svatopluk',
		'má svátek Matěj',
		'má svátek Liliana',
		'má svátek Dorota',
		'má svátek Alexandr',
		'má svátek Lumír',
		'má svátek Horymír',
	],
	[
		'má svátek Bedřich',
		'má svátek Anežka',
		'má svátek Kamil',
		'má svátek Stela',
		'má svátek Kazimír',
		'má svátek Miroslav',
		'má svátek Tomáš',
		'má svátek Gabriela',
		'má svátek Františka',
		'má svátek Viktorie',
		'má svátek Anděla',
		'má svátek Řehoř',
		'má svátek Růžena',
		'má svátek Rút a Matylda',
		'má svátek Ida',
		'má svátek Elena a Herbert',
		'má svátek Vlastimil',
		'má svátek Eduard',
		'má svátek Josef',
		'má svátek Světlana',
		'má svátek Radek',
		'má svátek Leona',
		'má svátek Ivona',
		'má svátek Gabriel',
		'má svátek Marián',
		'má svátek Emanuel',
		'má svátek Dita',
		'má svátek Soňa',
		'má svátek Taťána',
		'má svátek Arnošt',
		'má svátek Kvido',
	],
	[
		'má svátek Hugo',
		'má svátek Erika',
		'má svátek Richard',
		'má svátek Ivana',
		'má svátek Miroslava',
		'má svátek Vendula',
		'má svátek Heřman a Hermína',
		'má svátek Ema',
		'má svátek Dušan',
		'má svátek Darja',
		'má svátek Izabela',
		'má svátek Julius',
		'má svátek Aleš',
		'má svátek Vincenc',
		'má svátek Anastázie',
		'má svátek Irena',
		'má svátek Rudolf',
		'má svátek Valérie',
		'má svátek Rostislav',
		'má svátek Marcela',
		'má svátek Alexandra',
		'má svátek Evženie',
		'má svátek Vojtěch',
		'má svátek Jiří',
		'má svátek Marek',
		'má svátek Oto',
		'má svátek Jaroslav',
		'má svátek Vlastislav',
		'má svátek Robert',
		'má svátek Blahoslav',
	],
	[
		'je Svátek práce',
		'má svátek Zikmund',
		'má svátek Alexej',
		'má svátek Květoslav',
		'má svátek Klaudie',
		'má svátek Radoslav',
		'má svátek Stanislav',
		'je Den vítězství',
		'má svátek Ctibor',
		'má svátek Blažena',
		'má svátek Svatava',
		'má svátek Pankrác',
		'má svátek Servác',
		'má svátek Bonifác',
		'má svátek Žofie',
		'má svátek Přemysl',
		'má svátek Aneta',
		'má svátek Nataša',
		'má svátek Ivo',
		'má svátek Zbyšek',
		'má svátek Monika',
		'má svátek Emil',
		'má svátek Vladimír',
		'má svátek Jana',
		'má svátek Viola',
		'má svátek Filip',
		'má svátek Valdemar',
		'má svátek Vilém',
		'má svátek Maxmilián',
		'má svátek Ferdinand',
		'má svátek Kamila',
	],
	[
		'má svátek Laura',
		'má svátek Jarmil',
		'má svátek Tamara',
		'má svátek Dalibor',
		'má svátek Dobroslav',
		'má svátek Norbert',
		'má svátek Iveta a Slavoj',
		'má svátek Medard',
		'má svátek Stanislava',
		'má svátek Gita',
		'má svátek Bruno',
		'má svátek Antonie',
		'má svátek Antonín',
		'má svátek Roland',
		'má svátek Vít',
		'má svátek Zbyněk',
		'má svátek Adolf',
		'má svátek Milan',
		'má svátek Leoš',
		'má svátek Květa',
		'má svátek Alois',
		'má svátek Pavla',
		'má svátek Zdeňka',
		'má svátek Jan',
		'má svátek Ivan',
		'má svátek Adriana',
		'má svátek Ladislav',
		'má svátek Lubomír',
		'má svátek Petr a Pavel',
		'má svátek Šárka',
	],
	[
		'má svátek Jaroslava',
		'má svátek Patricie',
		'má svátek Radomír',
		'má svátek Prokop',
		'má svátek Cyril a Metoděj',
		'je Den upálení mistra Jana Husa',
		'má svátek Bohuslava',
		'má svátek Nora',
		'má svátek Drahoslava',
		'má svátek Libuše a Amálie',
		'má svátek Olga',
		'má svátek Bořek',
		'má svátek Markéta',
		'má svátek Karolína',
		'má svátek Jindřich',
		'má svátek Luboš',
		'má svátek Martina',
		'má svátek Drahomíra',
		'má svátek Čeněk',
		'má svátek Ilja',
		'má svátek Vítězslav',
		'má svátek Magdaléna',
		'má svátek Libor',
		'má svátek Kristýna',
		'má svátek Jakub',
		'má svátek Anna',
		'má svátek Věroslav',
		'má svátek Viktor',
		'má svátek Marta',
		'má svátek Bořivoj',
		'má svátek Ignác',
	],
	[
		'má svátek Oskar',
		'má svátek Gustav',
		'má svátek Miluše',
		'má svátek Dominik',
		'má svátek Kristián',
		'má svátek Oldřiška',
		'má svátek Lada',
		'má svátek Soběslav',
		'má svátek Roman',
		'má svátek Vavřinec',
		'má svátek Zuzana',
		'má svátek Klára',
		'má svátek Alena',
		'má svátek Alan',
		'má svátek Hana',
		'má svátek Jáchym',
		'má svátek Petra',
		'má svátek Helena',
		'má svátek Ludvík',
		'má svátek Bernard',
		'má svátek Johana',
		'má svátek Bohuslav',
		'má svátek Sandra',
		'má svátek Bartoloměj',
		'má svátek Radim',
		'má svátek Luděk',
		'má svátek Otakar',
		'má svátek Augustýn',
		'má svátek Evelína',
		'má svátek Vladěna',
		'má svátek Pavlína',
	],
	[
		'má svátek Linda a Samuel',
		'má svátek Adéla',
		'má svátek Bronislav',
		'má svátek Jindřiška',
		'má svátek Boris',
		'má svátek Boleslav',
		'má svátek Regína',
		'má svátek Mariana',
		'má svátek Daniela',
		'má svátek Irma',
		'má svátek Denisa',
		'má svátek Marie',
		'má svátek Lubor',
		'má svátek Radka',
		'má svátek Jolana',
		'má svátek Ludmila',
		'má svátek Naděžda',
		'má svátek Kryštof',
		'má svátek Zita',
		'má svátek Oleg',
		'má svátek Matouš',
		'má svátek Darina',
		'má svátek Berta',
		'má svátek Jaromír',
		'má svátek Zlata',
		'má svátek Andrea',
		'má svátek Jonáš',
		'má svátek Václav, je Den české státnosti',
		'má svátek Michal',
		'má svátek Jeroným',
	],
	[
		'má svátek Igor',
		'má svátek Olivie a Oliver',
		'má svátek Bohumil',
		'má svátek František',
		'má svátek Eliška',
		'má svátek Hanuš',
		'má svátek Justýna',
		'má svátek Věra',
		'má svátek Štefan a Sára',
		'má svátek Marina',
		'má svátek Andrej',
		'má svátek Marcel',
		'má svátek Renáta',
		'má svátek Agáta',
		'má svátek Tereza',
		'má svátek Havel',
		'má svátek Hedvika',
		'má svátek Lukáš',
		'má svátek Michaela',
		'má svátek Vendelín',
		'má svátek Brigita',
		'má svátek Sabina',
		'má svátek Teodor',
		'má svátek Nina',
		'má svátek Beáta',
		'má svátek Erik',
		'má svátek Šarlota a Zoe',
		'je Den vzniku samostatného československého státu',
		'má svátek Silvie',
		'má svátek Tadeáš',
		'má svátek Štěpánka',
	],
	[
		'má svátek Felix',
		'je Památka zesnulých',
		'má svátek Hubert',
		'má svátek Karel',
		'má svátek Miriam',
		'má svátek Liběna',
		'má svátek Saskie',
		'má svátek Bohumír',
		'má svátek Bohdan',
		'má svátek Evžen',
		'má svátek Martin',
		'má svátek Benedikt',
		'má svátek Tibor',
		'má svátek Sáva',
		'má svátek Leopold',
		'má svátek Otmar',
		'má svátek Mahulena, je Den boje za svobodu a demokracii',
		'má svátek Romana',
		'má svátek Alžběta',
		'má svátek Nikola',
		'má svátek Albert',
		'má svátek Cecílie',
		'má svátek Klement',
		'má svátek Emílie',
		'má svátek Kateřina',
		'má svátek Artur',
		'má svátek Xenie',
		'má svátek René',
		'má svátek Zina',
		'má svátek Ondřej',
	],
	[
		'má svátek Iva',
		'má svátek Blanka',
		'má svátek Svatoslav',
		'má svátek Barbora',
		'má svátek Jitka',
		'má svátek Mikuláš',
		'má svátek Benjamín',
		'má svátek Květoslava',
		'má svátek Vratislav',
		'má svátek Julie',
		'má svátek Dana',
		'má svátek Simona',
		'má svátek Lucie',
		'má svátek Lýdie',
		'má svátek Radana',
		'má svátek Albína',
		'má svátek Daniel',
		'má svátek Miloslav',
		'má svátek Ester',
		'má svátek Dagmar',
		'má svátek Natálie',
		'má svátek Šimon',
		'má svátek Vlasta',
		'má svátek Adam a Eva, je Štědrý den',
		'je 1. svátek vánoční',
		'má svátek Štěpán, je 2. svátek vánoční',
		'má svátek Žaneta',
		'má svátek Bohumila',
		'má svátek Judita',
		'má svátek David',
		'má svátek Silvestr',
	],
];
