export const NAMEDAYS: string[][] = [
	[
		'je Nový rok, Den obnovy samostatného českého státu',
		'má svátek Karina',
		'má svátek Radmila',
		'má svátek Diana',
		'má svátek Dalimil',
		'jsou Tři králové',
		'má svátek Vilma',
		'má svátek Čestmír',
		'má svátek Vladan',
		'má svátek Břetislav',
		'má svátek Bohdana',
		'má svátek Pravoslav',
		'má svátek Edita',
		'má svátek Radovan',
		'má svátek Alice',
		'má svátek Ctirad',
		'má svátek Drahoslav',
		'má svátek Vladislav',
		'má svátek Doubravka',
		'má svátek Ilona',
		'má svátek Běla',
		'má svátek Slavomír',
		'má svátek Zdeněk',
		'má svátek Milena',
		'má svátek Miloš',
		'má svátek Zora',
		'má svátek Ingrid',
		'má svátek Otýlie',
		'má svátek Zdislava',
		'má svátek Robin',
		'má svátek Marika',
	],
	[
		'má svátek Hynek',
		'má svátek Nela',
		'má svátek Blažej',
		'má svátek Jarmila',
		'má svátek Dobromila',
		'má svátek Vanda',
		'má svátek Veronika',
		'má svátek Milada',
		'má svátek Apolena',
		'má svátek Mojmír',
		'má svátek Božena',
		'má svátek Slavěna',
		'má svátek Věnceslav',
		'má svátek Valentýn',
		'má svátek Jiřina',
		'má svátek Ljuba',
		'má svátek Miloslava',
		'má svátek Gizela',
		'má svátek Patrik',
		'má svátek Oldřich',
		'má svátek Lenka',
		'má svátek Petr',
		'má svátek Svatopluk',
		'má svátek Matěj',
		'má svátek Liliana',
		'má svátek Dorota',
		'má svátek Alexandr',
		'má svátek Lumír',
		'má svátek Horymír',
	],
	[
		'má svátek Bedřich',
		'má svátek Anežka',
		'má svátek Kamil',
		'má svátek Stela',
		'má svátek Kazimír',
		'má svátek Miroslav',
		'má svátek Tomáš',
		'má svátek Gabriela',
		'má svátek Františka',
		'má svátek Viktorie',
		'má svátek Anděla',
		'má svátek Řehoř',
		'má svátek Růžena',
		'má svátek Rút a Matylda',
		'má svátek Ida',
		'má svátek Elena a Herbert',
		'má svátek Vlastimil',
		'má svátek Eduard',
		'má svátek Josef',
		'má svátek Světlana',
		'má svátek Radek',
		'má svátek Leona',
		'má svátek Ivona',
		'má svátek Gabriel',
		'má svátek Marián',
		'má svátek Emanuel',
		'má svátek Dita',
		'má svátek Soňa',
		'má svátek Taťána',
		'má svátek Arnošt',
		'má svátek Kvido',
	],
	[
		'má svátek Hugo',
		'má svátek Erika',
		'má svátek Richard',
		'má svátek Ivana',
		'má svátek Miroslava',
		'má svátek Vendula',
		'má svátek Heřman a Hermína',
		'má svátek Ema',
		'má svátek Dušan',
		'má svátek Darja',
		'má svátek Izabela',
		'má svátek Julius',
		'má svátek Aleš',
		'má svátek Vincenc',
		'má svátek Anastázie',
		'má svátek Irena',
		'má svátek Rudolf',
		'má svátek Valérie',
		'má svátek Rostislav',
		'má svátek Marcela',
		'má svátek Alexandra',
		'má svátek Evženie',
		'má svátek Vojtěch',
		'má svátek Jiří',
		'má svátek Marek',
		'má svátek Oto',
		'má svátek Jaroslav',
		'má svátek Vlastislav',
		'má svátek Robert',
		'má svátek Blahoslav',
	],
	[
		'je Svátek práce',
		'má svátek Zikmund',
		'má svátek Alexej',
		'má svátek Květoslav',
		'má svátek Klaudie',
		'má svátek Radoslav',
		'má svátek Stanislav',
		'je Den vítězství',
		'má svátek Ctibor',
		'má svátek Blažena',
		'má svátek Svatava',
		'má svátek Pankrác',
		'má svátek Servác',
		'má svátek Bonifác',
		'má svátek Žofie',
		'má svátek Přemysl',
		'má svátek Aneta',
		'má svátek Nataša',
		'má svátek Ivo',
		'má svátek Zbyšek',
		'má svátek Monika',
		'má svátek Emil',
		'má svátek Vladimír',
		'má svátek Jana',
		'má svátek Viola',
		'má svátek Filip',
		'má svátek Valdemar',
		'má svátek Vilém',
		'má svátek Maxmilián',
		'má svátek Ferdinand',
		'má svátek Kamila',
	],
	[
		'má svátek Laura',
		'má svátek Jarmil',
		'má svátek Tamara',
		'má svátek Dalibor',
		'má svátek Dobroslav',
		'má svátek Norbert',
		'má svátek Iveta a Slavoj',
		'má svátek Medard',
		'má svátek Stanislava',
		'má svátek Gita',
		'má svátek Bruno',
		'má svátek Antonie',
		'má svátek Antonín',
		'má svátek Roland',
		'má svátek Vít',
		'má svátek Zbyněk',
		'má svátek Adolf',
		'má svátek Milan',
		'má svátek Leoš',
		'má svátek Květa',
		'má svátek Alois',
		'má svátek Pavla',
		'má svátek Zdeňka',
		'má svátek Jan',
		'má svátek Ivan',
		'má svátek Adriana',
		'má svátek Ladislav',
		'má svátek Lubomír',
		'má svátek Petr a Pavel',
		'má svátek Šárka',
	],
	[
		'má svátek Jaroslava',
		'má svátek Patricie',
		'má svátek Radomír',
		'má svátek Prokop',
		'má svátek Cyril a Metoděj',
		'je Den upálení mistra Jana Husa',
		'má svátek Bohuslava',
		'má svátek Nora',
		'má svátek Drahoslava',
		'má svátek Libuše a Amálie',
		'má svátek Olga',
		'má svátek Bořek',
		'má svátek Markéta',
		'má svátek Karolína',
		'má svátek Jindřich',
		'má svátek Luboš',
		'má svátek Martina',
		'má svátek Drahomíra',
		'má svátek Čeněk',
		'má svátek Ilja',
		'má svátek Vítězslav',
		'má svátek Magdaléna',
		'má svátek Libor',
		'má svátek Kristýna',
		'má svátek Jakub',
		'má svátek Anna',
		'má svátek Věroslav',
		'má svátek Viktor',
		'má svátek Marta',
		'má svátek Bořivoj',
		'má svátek Ignác',
	],
	[
		'má svátek Oskar',
		'má svátek Gustav',
		'má svátek Miluše',
		'má svátek Dominik',
		'má svátek Kristián',
		'má svátek Oldřiška',
		'má svátek Lada',
		'má svátek Soběslav',
		'má svátek Roman',
		'má svátek Vavřinec',
		'má svátek Zuzana',
		'má svátek Klára',
		'má svátek Alena',
		'má svátek Alan',
		'má svátek Hana',
		'má svátek Jáchym',
		'má svátek Petra',
		'má svátek Helena',
		'má svátek Ludvík',
		'má svátek Bernard',
		'má svátek Johana',
		'má svátek Bohuslav',
		'má svátek Sandra',
		'má svátek Bartoloměj',
		'má svátek Radim',
		'má svátek Luděk',
		'má svátek Otakar',
		'má svátek Augustýn',
		'má svátek Evelína',
		'má svátek Vladěna',
		'má svátek Pavlína',
	],
	[
		'má svátek Linda a Samuel',
		'má svátek Adéla',
		'má svátek Bronislav',
		'má svátek Jindřiška',
		'má svátek Boris',
		'má svátek Boleslav',
		'má svátek Regína',
		'má svátek Mariana',
		'má svátek Daniela',
		'má svátek Irma',
		'má svátek Denisa',
		'má svátek Marie',
		'má svátek Lubor',
		'má svátek Radka',
		'má svátek Jolana',
		'má svátek Ludmila',
		'má svátek Naděžda',
		'má svátek Kryštof',
		'má svátek Zita',
		'má svátek Oleg',
		'má svátek Matouš',
		'má svátek Darina',
		'má svátek Berta',
		'má svátek Jaromír',
		'má svátek Zlata',
		'má svátek Andrea',
		'má svátek Jonáš',
		'má svátek Václav, je Den české státnosti',
		'má svátek Michal',
		'má svátek Jeroným',
	],
	[
		'má svátek Igor',
		'má svátek Olivie a Oliver',
		'má svátek Bohumil',
		'má svátek František',
		'má svátek Eliška',
		'má svátek Hanuš',
		'má svátek Justýna',
		'má svátek Věra',
		'má svátek Štefan a Sára',
		'má svátek Marina',
		'má svátek Andrej',
		'má svátek Marcel',
		'má svátek Renáta',
		'má svátek Agáta',
		'má svátek Tereza',
		'má svátek Havel',
		'má svátek Hedvika',
		'má svátek Lukáš',
		'má svátek Michaela',
		'má svátek Vendelín',
		'má svátek Brigita',
		'má svátek Sabina',
		'má svátek Teodor',
		'má svátek Nina',
		'má svátek Beáta',
		'má svátek Erik',
		'má svátek Šarlota a Zoe',
		'je Den vzniku samostatného československého státu',
		'má svátek Silvie',
		'má svátek Tadeáš',
		'má svátek Štěpánka',
	],
	[
		'má svátek Felix',
		'je Památka zesnulých',
		'má svátek Hubert',
		'má svátek Karel',
		'má svátek Miriam',
		'má svátek Liběna',
		'má svátek Saskie',
		'má svátek Bohumír',
		'má svátek Bohdan',
		'má svátek Evžen',
		'má svátek Martin',
		'má svátek Benedikt',
		'má svátek Tibor',
		'má svátek Sáva',
		'má svátek Leopold',
		'má svátek Otmar',
		'má svátek Mahulena, je Den boje za svobodu a demokracii',
		'má svátek Romana',
		'má svátek Alžběta',
		'má svátek Nikola',
		'má svátek Albert',
		'má svátek Cecílie',
		'má svátek Klement',
		'má svátek Emílie',
		'má svátek Kateřina',
		'má svátek Artur',
		'má svátek Xenie',
		'má svátek René',
		'má svátek Zina',
		'má svátek Ondřej',
	],
	[
		'má svátek Iva',
		'má svátek Blanka',
		'má svátek Svatoslav',
		'má svátek Barbora',
		'má svátek Jitka',
		'má svátek Mikuláš',
		'má svátek Benjamín',
		'má svátek Květoslava',
		'má svátek Vratislav',
		'má svátek Julie',
		'má svátek Dana',
		'má svátek Simona',
		'má svátek Lucie',
		'má svátek Lýdie',
		'má svátek Radana',
		'má svátek Albína',
		'má svátek Daniel',
		'má svátek Miloslav',
		'má svátek Ester',
		'má svátek Dagmar',
		'má svátek Natálie',
		'má svátek Šimon',
		'má svátek Vlasta',
		'má svátek Adam a Eva, je Štědrý den',
		'je 1. svátek vánoční',
		'má svátek Štěpán, je 2. svátek vánoční',
		'má svátek Žaneta',
		'má svátek Bohumila',
		'má svátek Judita',
		'má svátek David',
		'má svátek Silvestr',
	],
];

export const NAMEDAYS_EN: string[][] = [
	[
		'is the New Year, Day of Restoration of the Independent Czech State',
		'is the name day of Karina',
		'is the name day of Radmila',
		'is the name day of Diana',
		'is the name day of Dalimil',
		'is the day of the Three Kings',
		'is the name day of Vilma',
		'is the name day of Čestmír',
		'is the name day of Vladan',
		'is the name day of Břetislav',
		'is the name day of Bohdana',
		'is the name day of Pravoslav',
		'is the name day of Edita',
		'is the name day of Radovan',
		'is the name day of Alice',
		'is the name day of Ctirad',
		'is the name day of Drahoslav',
		'is the name day of Vladislav',
		'is the name day of Doubravka',
		'is the name day of Ilona',
		'is the name day of Běla',
		'is the name day of Slavomír',
		'is the name day of Zdeněk',
		'is the name day of Milena',
		'is the name day of Miloš',
		'is the name day of Zora',
		'is the name day of Ingrid',
		'is the name day of Otýlie',
		'is the name day of Zdislava',
		'is the name day of Robin',
		'is the name day of Marika',
	],
	[
		'is the name day of Hynek',
		'is the name day of Nela',
		'is the name day of Blažej',
		'is the name day of Jarmila',
		'is the name day of Dobromila',
		'is the name day of Vanda',
		'is the name day of Veronika',
		'is the name day of Milada',
		'is the name day of Apolena',
		'is the name day of Mojmír',
		'is the name day of Božena',
		'is the name day of Slavěna',
		'is the name day of Věnceslav',
		'is the name day of Valentýn',
		'is the name day of Jiřina',
		'is the name day of Ljuba',
		'is the name day of Miloslava',
		'is the name day of Gizela',
		'is the name day of Patrik',
		'is the name day of Oldřich',
		'is the name day of Lenka',
		'is the name day of Petr',
		'is the name day of Svatopluk',
		'is the name day of Matěj',
		'is the name day of Liliana',
		'is the name day of Dorota',
		'is the name day of Alexandr',
		'is the name day of Lumír',
		'is the name day of Horymír',
	],
	[
		'is the name day of Bedřich',
		'is the name day of Anežka',
		'is the name day of Kamil',
		'is the name day of Stela',
		'is the name day of Kazimír',
		'is the name day of Miroslav',
		'is the name day of Tomáš',
		'is the name day of Gabriela',
		'is the name day of Františka',
		'is the name day of Viktorie',
		'is the name day of Anděla',
		'is the name day of Řehoř',
		'is the name day of Růžena',
		'is the name day of Rút and Matylda',
		'is the name day of Ida',
		'is the name day of Elena and Herbert',
		'is the name day of Vlastimil',
		'is the name day of Eduard',
		'is the name day of Josef',
		'is the name day of Světlana',
		'is the name day of Radek',
		'is the name day of Leona',
		'is the name day of Ivona',
		'is the name day of Gabriel',
		'is the name day of Marián',
		'is the name day of Emanuel',
		'is the name day of Dita',
		'is the name day of Soňa',
		'is the name day of Taťána',
		'is the name day of Arnošt',
		'is the name day of Kvido',
	],
	[
		'is the name day of Hugo',
		'is the name day of Erika',
		'is the name day of Richard',
		'is the name day of Ivana',
		'is the name day of Miroslava',
		'is the name day of Vendula',
		'is the name day of Heřman and Hermína',
		'is the name day of Ema',
		'is the name day of Dušan',
		'is the name day of Darja',
		'is the name day of Izabela',
		'is the name day of Julius',
		'is the name day of Aleš',
		'is the name day of Vincenc',
		'is the name day of Anastázie',
		'is the name day of Irena',
		'is the name day of Rudolf',
		'is the name day of Valérie',
		'is the name day of Rostislav',
		'is the name day of Marcela',
		'is the name day of Alexandra',
		'is the name day of Evženie',
		'is the name day of Vojtěch',
		'is the name day of Jiří',
		'is the name day of Marek',
		'is the name day of Oto',
		'is the name day of Jaroslav',
		'is the name day of Vlastislav',
		'is the name day of Robert',
		'is the name day of Blahoslav',
	],
	[
		'is the Labour Day',
		'is the name day of Zikmund',
		'is the name day of Alexej',
		'is the name day of Květoslav',
		'is the name day of Klaudie',
		'is the name day of Radoslav',
		'is the name day of Stanislav',
		'is the Liberation Day',
		'is the name day of Ctibor',
		'is the name day of Blažena',
		'is the name day of Svatava',
		'is the name day of Pankrác',
		'is the name day of Servác',
		'is the name day of Bonifác',
		'is the name day of Žofie',
		'is the name day of Přemysl',
		'is the name day of Aneta',
		'is the name day of Nataša',
		'is the name day of Ivo',
		'is the name day of Zbyšek',
		'is the name day of Monika',
		'is the name day of Emil',
		'is the name day of Vladimír',
		'is the name day of Jana',
		'is the name day of Viola',
		'is the name day of Filip',
		'is the name day of Valdemar',
		'is the name day of Vilém',
		'is the name day of Maxmilián',
		'is the name day of Ferdinand',
		'is the name day of Kamila',
	],
	[
		'is the name day of Laura',
		'is the name day of Jarmil',
		'is the name day of Tamara',
		'is the name day of Dalibor',
		'is the name day of Dobroslav',
		'is the name day of Norbert',
		'is the name day of Iveta and Slavoj',
		'is the name day of Medard',
		'is the name day of Stanislava',
		'is the name day of Gita',
		'is the name day of Bruno',
		'is the name day of Antonie',
		'is the name day of Antonín',
		'is the name day of Roland',
		'is the name day of Vít',
		'is the name day of Zbyněk',
		'is the name day of Adolf',
		'is the name day of Milan',
		'is the name day of Leoš',
		'is the name day of Květa',
		'is the name day of Alois',
		'is the name day of Pavla',
		'is the name day of Zdeňka',
		'is the name day of Jan',
		'is the name day of Ivan',
		'is the name day of Adriana',
		'is the name day of Ladislav',
		'is the name day of Lubomír',
		'is the name day of Petr and Pavel',
		'is the name day of Šárka',
	],
	[
		'is the name day of Jaroslava',
		'is the name day of Patricie',
		'is the name day of Radomír',
		'is the name day of Prokop',
		'is the name day of Cyril and Metoděj',
		'is the Day of Burning Jan Hus',
		'is the name day of Bohuslava',
		'is the name day of Nora',
		'is the name day of Drahoslava',
		'is the name day of Libuše and Amálie',
		'is the name day of Olga',
		'is the name day of Bořek',
		'is the name day of Markéta',
		'is the name day of Karolína',
		'is the name day of Jindřich',
		'is the name day of Luboš',
		'is the name day of Martina',
		'is the name day of Drahomíra',
		'is the name day of Čeněk',
		'is the name day of Ilja',
		'is the name day of Vítězslav',
		'is the name day of Magdaléna',
		'is the name day of Libor',
		'is the name day of Kristýna',
		'is the name day of Jakub',
		'is the name day of Anna',
		'is the name day of Věroslav',
		'is the name day of Viktor',
		'is the name day of Marta',
		'is the name day of Bořivoj',
		'is the name day of Ignác',
	],
	[
		'is the name day of Oskar',
		'is the name day of Gustav',
		'is the name day of Miluše',
		'is the name day of Dominik',
		'is the name day of Kristián',
		'is the name day of Oldřiška',
		'is the name day of Lada',
		'is the name day of Soběslav',
		'is the name day of Roman',
		'is the name day of Vavřinec',
		'is the name day of Zuzana',
		'is the name day of Klára',
		'is the name day of Alena',
		'is the name day of Alan',
		'is the name day of Hana',
		'is the name day of Jáchym',
		'is the name day of Petra',
		'is the name day of Helena',
		'is the name day of Ludvík',
		'is the name day of Bernard',
		'is the name day of Johana',
		'is the name day of Bohuslav',
		'is the name day of Sandra',
		'is the name day of Bartoloměj',
		'is the name day of Radim',
		'is the name day of Luděk',
		'is the name day of Otakar',
		'is the name day of Augustýn',
		'is the name day of Evelína',
		'is the name day of Vladěna',
		'is the name day of Pavlína',
	],
	[
		'is the name day of Linda and Samuel',
		'is the name day of Adéla',
		'is the name day of Bronislav',
		'is the name day of Jindřiška',
		'is the name day of Boris',
		'is the name day of Boleslav',
		'is the name day of Regína',
		'is the name day of Mariana',
		'is the name day of Daniela',
		'is the name day of Irma',
		'is the name day of Denisa',
		'is the name day of Marie',
		'is the name day of Lubor',
		'is the name day of Radka',
		'is the name day of Jolana',
		'is the name day of Ludmila',
		'is the name day of Naděžda',
		'is the name day of Kryštof',
		'is the name day of Zita',
		'is the name day of Oleg',
		'is the name day of Matouš',
		'is the name day of Darina',
		'is the name day of Berta',
		'is the name day of Jaromír',
		'is the name day of Zlata',
		'is the name day of Andrea',
		'is the name day of Jonáš',
		'is the name day of Václav, is Statehood Day',
		'is the name day of Michal',
		'is the name day of Jeroným',
	],
	[
		'is the name day of Igor',
		'is the name day of Olivie and Oliver',
		'is the name day of Bohumil',
		'is the name day of František',
		'is the name day of Eliška',
		'is the name day of Hanuš',
		'is the name day of Justýna',
		'is the name day of Věra',
		'is the name day of Štefan and Sára',
		'is the name day of Marina',
		'is the name day of Andrej',
		'is the name day of Marcel',
		'is the name day of Renáta',
		'is the name day of Agáta',
		'is the name day of Tereza',
		'is the name day of Havel',
		'is the name day of Hedvika',
		'is the name day of Lukáš',
		'is the name day of Michaela',
		'is the name day of Vendelín',
		'is the name day of Brigita',
		'is the name day of Sabina',
		'is the name day of Teodor',
		'is the name day of Nina',
		'is the name day of Beáta',
		'is the name day of Erik',
		'is the name day of Šarlota and Zoe',
		'is the Independent Czechoslovak State Day',
		'is the name day of Silvie',
		'is the name day of Tadeáš',
		'is the name day of Štěpánka',
	],
	[
		'is the name day of Felix',
		'is the All Souls’ Day',
		'is the name day of Hubert',
		'is the name day of Karel',
		'is the name day of Miriam',
		'is the name day of Liběna',
		'is the name day of Saskie',
		'is the name day of Bohumír',
		'is the name day of Bohdan',
		'is the name day of Evžen',
		'is the name day of Martin',
		'is the name day of Benedikt',
		'is the name day of Tibor',
		'is the name day of Sáva',
		'is the name day of Leopold',
		'is the name day of Otmar',
		'is the name day of Mahulena, is Struggle for Freedom and Democracy Day',
		'is the name day of Romana',
		'is the name day of Alžběta',
		'is the name day of Nikola',
		'is the name day of Albert',
		'is the name day of Cecílie',
		'is the name day of Klement',
		'is the name day of Emílie',
		'is the name day of Kateřina',
		'is the name day of Artur',
		'is the name day of Xenie',
		'is the name day of René',
		'is the name day of Zina',
		'is the name day of Ondřej',
	],
	[
		'is the name day of Iva',
		'is the name day of Blanka',
		'is the name day of Svatoslav',
		'is the name day of Barbora',
		'is the name day of Jitka',
		'is the name day of Mikuláš',
		'is the name day of Benjamín',
		'is the name day of Květoslava',
		'is the name day of Vratislav',
		'is the name day of Julie',
		'is the name day of Dana',
		'is the name day of Simona',
		'is the name day of Lucie',
		'is the name day of Lýdie',
		'is the name day of Radana',
		'is the name day of Albína',
		'is the name day of Daniel',
		'is the name day of Miloslav',
		'is the name day of Ester',
		'is the name day of Dagmar',
		'is the name day of Natálie',
		'is the name day of Šimon',
		'is the name day of Vlasta',
		'is the name day of Adam and Eva, is Christmas Eve',
		'is Christmas',
		'is the name day of Štěpán, is Boxing Day',
		'is the name day of Žaneta',
		'is the name day of Bohumila',
		'is the name day of Judita',
		'is the name day of David',
		'is the name day of Silvestr',
	],
];
